USE aws_abex;

DROP TABLE IF EXISTS LINKVISITEDUSERLIST;
DROP TABLE IF EXISTS LINKLIST;

CREATE TABLE LINKLIST (
	originURL VARCHAR(30) NOT NULL PRIMARY KEY,
	destinationURL MEDIUMTEXT NOT NULL,
	visited INT NOT NULL DEFAULT 0,
	visits_max INT NOT NULL,
	created_by VARCHAR(30) NOT NULL,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LINKVISITEDUSERLIST (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	originURL VARCHAR(30) NOT NULL,
	user_ip VARCHAR(30) NOT NULL,
	visited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (originURL) REFERENCES LINKLIST(originURL) ON DELETE CASCADE
);
