USE aws_abex;

DROP TABLE IF EXISTS LINKLIST;
CREATE TABLE LINKLIST (
	originURL VARCHAR(30) NOT NULL PRIMARY KEY,
	destinationURL MEDIUMTEXT NOT NULL,
	visited INT NOT NULL DEFAULT 0,
	visits_max INT NOT NULL,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
